/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author rohit
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        getRecords();
        Container c = getContentPane();
        c.setBackground(new Color(0, 153, 153));
    }

    public void getRecords() {
        try {
            Connection con = DBConncection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from fees_details order by reciept_no desc limit 1");
            ResultSet rs = pst.executeQuery();
            rs.next();

            txt_receiptNo.setText(rs.getString("reciept_no"));
            txxt_paymentMode.setText(rs.getString("payment_mode"));

            String paymentmode = rs.getString("payment_mode");

            if (paymentmode.equalsIgnoreCase("cash")) {
                lblbankname.setText("cheque no ");
                txxt_chequeDDno.setText("-");
                txxt_bankname.setText("-");

            }
            if (paymentmode.equalsIgnoreCase("cheque")) {
                lblbankname.setText("cheque no ");
                txxt_chequeDDno.setText(rs.getString("cheque_no"));
                txxt_bankname.setText(rs.getString("bank_name"));

            }
            if (paymentmode.equalsIgnoreCase("dd")) {
                lblbankname.setText("dd no ");
                txxt_chequeDDno.setText(rs.getString("dd_no"));
                txxt_bankname.setText(rs.getString("bank_name"));

            }
            if (paymentmode.equalsIgnoreCase("card")) {
                lblbankname.setText("cheque no ");
                txxt_chequeDDno.setText("-");
                txxt_bankname.setText(rs.getString("bank_name"));

            }
            txxt_recivedfrom.setText(rs.getString("student_name"));
            txxt_date.setText(rs.getString("date"));
            txxt_gstinn.setText(rs.getString("gstin"));
            txxt_year1.setText(rs.getString("year1"));
            txxt_year2.setText(rs.getString("year2"));

            txxt_initialamount.setText(rs.getString("amount"));
            txxt_getcgst.setText(rs.getString("cgst"));
            txxt_getsgst.setText(rs.getString("sgst"));
            txxt_totalamount.setText(rs.getString("total_amount"));
            txxt_totalinwordsss.setText(rs.getString("total_in_words"));
            txxt_remarkget.setText(rs.getString("remark"));
            txxt_coursenaame1.setText(rs.getString("courses"));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelsidebar = new javax.swing.JPanel();
        Panelview = new javax.swing.JPanel();
        btnview = new javax.swing.JLabel();
        Panelback = new javax.swing.JPanel();
        btnback = new javax.swing.JLabel();
        Panesearch = new javax.swing.JPanel();
        btnsearch = new javax.swing.JLabel();
        Paneledit = new javax.swing.JPanel();
        btnedit = new javax.swing.JLabel();
        Panellogout = new javax.swing.JPanel();
        btnlogout = new javax.swing.JLabel();
        Panelhome = new javax.swing.JPanel();
        btnhome = new javax.swing.JLabel();
        Panelcourse = new javax.swing.JPanel();
        btncourse = new javax.swing.JLabel();
        panelprint = new javax.swing.JPanel();
        btnprint = new javax.swing.JLabel();
        paneleditlast = new javax.swing.JPanel();
        btnedditlast = new javax.swing.JLabel();
        panelprinttt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_receiptNo = new javax.swing.JLabel();
        txxt_paymentMode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txxt_chequeDDno = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblchequename = new javax.swing.JLabel();
        txxt_recivedfrom = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblbankname = new javax.swing.JLabel();
        txxt_bankname = new javax.swing.JLabel();
        txxt_dash = new javax.swing.JLabel();
        txxt_year2 = new javax.swing.JLabel();
        txxt_year1 = new javax.swing.JLabel();
        txxt_date = new javax.swing.JLabel();
        txxt_gstinn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txxt_getsgst = new javax.swing.JLabel();
        txxt_totalinwordsss = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txxt_cgst = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txxt_coursenaame1 = new javax.swing.JLabel();
        txxt_initialamount = new javax.swing.JLabel();
        txxt_getcgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txxt_sgst1 = new javax.swing.JLabel();
        txxt_total1 = new javax.swing.JLabel();
        txxt_remarkget = new javax.swing.JLabel();
        txxt_totalamount = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txxt_total4 = new javax.swing.JLabel();
        txxt_total5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelsidebar.setBackground(new java.awt.Color(0, 102, 102));
        Panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelview.setBackground(new java.awt.Color(0, 102, 102));
        Panelview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panelview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelviewMouseEntered(evt);
            }
        });
        Panelview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnview.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnview.setForeground(new java.awt.Color(255, 255, 255));
        btnview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/view all record.png"))); // NOI18N
        btnview.setText("View All Record");
        btnview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnviewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewMouseExited(evt);
            }
        });
        Panelview.add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 240, -1));

        Panelsidebar.add(Panelview, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 290, 80));

        Panelback.setBackground(new java.awt.Color(0, 102, 102));
        Panelback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelbackMouseEntered(evt);
            }
        });
        Panelback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/left-arrow.png"))); // NOI18N
        btnback.setText(" Back ");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        Panelback.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, -1));

        Panelsidebar.add(Panelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 290, 80));

        Panesearch.setBackground(new java.awt.Color(0, 102, 102));
        Panesearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panesearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanesearchMouseEntered(evt);
            }
        });
        Panesearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsearch.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/search2.png"))); // NOI18N
        btnsearch.setText("Search Record");
        btnsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchMouseExited(evt);
            }
        });
        Panesearch.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 230, -1));

        Panelsidebar.add(Panesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 290, 80));

        Paneledit.setBackground(new java.awt.Color(0, 102, 102));
        Paneledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Paneledit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PaneleditMouseEntered(evt);
            }
        });
        Paneledit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnedit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/edit2.png"))); // NOI18N
        btnedit.setText("Edit Course");
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
        });
        Paneledit.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 230, 60));

        Panelsidebar.add(Paneledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 290, 80));

        Panellogout.setBackground(new java.awt.Color(0, 102, 102));
        Panellogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanellogoutMouseEntered(evt);
            }
        });
        Panellogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/logout.png"))); // NOI18N
        btnlogout.setText(" Log Out");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });
        Panellogout.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, -1));

        Panelsidebar.add(Panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 290, 80));

        Panelhome.setBackground(new java.awt.Color(0, 102, 102));
        Panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelhomeMouseEntered(evt);
            }
        });
        Panelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/home.png"))); // NOI18N
        btnhome.setText("  HOME");
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhomeMouseExited(evt);
            }
        });
        Panelhome.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 200, 60));

        Panelsidebar.add(Panelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 290, 80));

        Panelcourse.setBackground(new java.awt.Color(0, 102, 102));
        Panelcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Panelcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelcourseMouseEntered(evt);
            }
        });
        Panelcourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncourse.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btncourse.setForeground(new java.awt.Color(255, 255, 255));
        btncourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/list.png"))); // NOI18N
        btncourse.setText("Course List");
        btncourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncourseMouseExited(evt);
            }
        });
        Panelcourse.add(btncourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 190, -1));

        Panelsidebar.add(Panelcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 290, 80));

        panelprint.setBackground(new java.awt.Color(0, 102, 102));
        panelprint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelprintMouseEntered(evt);
            }
        });
        panelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnprint.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnprint.setForeground(new java.awt.Color(255, 255, 255));
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/printer-.png"))); // NOI18N
        btnprint.setText(" Print");
        btnprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnprintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnprintMouseExited(evt);
            }
        });
        panelprint.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 60));

        Panelsidebar.add(panelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 200, 70));

        paneleditlast.setBackground(new java.awt.Color(0, 102, 102));
        paneleditlast.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        paneleditlast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneleditlastMouseEntered(evt);
            }
        });
        paneleditlast.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnedditlast.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnedditlast.setForeground(new java.awt.Color(255, 255, 255));
        btnedditlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/edit2.png"))); // NOI18N
        btnedditlast.setText(" Edit");
        btnedditlast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnedditlastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnedditlastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnedditlastMouseExited(evt);
            }
        });
        paneleditlast.add(btnedditlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 70));

        Panelsidebar.add(paneleditlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 200, 70));

        getContentPane().add(Panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 1030));

        panelprinttt.setBackground(new java.awt.Color(255, 255, 255));
        panelprinttt.setForeground(new java.awt.Color(102, 0, 255));
        panelprinttt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management/image/sdsmlogo2.jpg"))); // NOI18N
        panelprinttt.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 140));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        panelprinttt.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1220, 10));

        txt_receiptNo.setText("Receipt No : ");
        panelprinttt.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, 20));

        txxt_paymentMode.setText("Payment Mode : ");
        panelprinttt.add(txxt_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, 20));

        jLabel7.setText("Receipt No : ");
        panelprinttt.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 20));

        jLabel9.setText("Payment Mode : ");
        panelprinttt.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 20));

        txxt_chequeDDno.setText("cheque_DD No :");
        panelprinttt.add(txxt_chequeDDno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 130, 20));

        jLabel11.setText("The Following Payment In The Office For The Year  : ");
        panelprinttt.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 290, 20));

        lblchequename.setText("cheque_DD No :");
        panelprinttt.add(lblchequename, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 20));

        txxt_recivedfrom.setText("Recived From :");
        panelprinttt.add(txxt_recivedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 150, 20));

        jLabel14.setText("Recived From :");
        panelprinttt.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 90, 20));

        lblbankname.setText("Bank Name  :");
        panelprinttt.add(lblbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 90, 20));

        txxt_bankname.setText("Bank Name  :");
        panelprinttt.add(txxt_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 140, 20));

        txxt_dash.setText("-");
        panelprinttt.add(txxt_dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 20, 20));

        txxt_year2.setText("2022");
        panelprinttt.add(txxt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 50, 20));

        txxt_year1.setText("2021");
        panelprinttt.add(txxt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 40, 20));

        txxt_date.setText("Date :");
        panelprinttt.add(txxt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 120, -1));

        txxt_gstinn.setText("GSTIN :");
        panelprinttt.add(txxt_gstinn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 130, -1));

        jLabel8.setText("Date :");
        panelprinttt.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 40, -1));

        jLabel10.setText("GSTIN :");
        panelprinttt.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 40, -1));
        panelprinttt.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 760, 10));
        panelprinttt.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 760, 10));

        jLabel5.setText("Amount (Rs)");
        panelprinttt.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 80, -1));

        txxt_getsgst.setText("sgst");
        panelprinttt.add(txxt_getsgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 120, -1));

        txxt_totalinwordsss.setText("Total In Words : ");
        panelprinttt.add(txxt_totalinwordsss, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 300, -1));

        jLabel16.setText("SR.NO ");
        panelprinttt.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel17.setText("Heads");
        panelprinttt.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 40, -1));

        txxt_cgst.setText("CGST 18%");
        panelprinttt.add(txxt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 80, 20));

        jLabel19.setText("1");
        panelprinttt.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 30, -1));

        txxt_coursenaame1.setText("Course Name");
        panelprinttt.add(txxt_coursenaame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 120, -1));

        txxt_initialamount.setText("Initial Aamount");
        panelprinttt.add(txxt_initialamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 120, -1));

        txxt_getcgst.setText("cgst");
        panelprinttt.add(txxt_getcgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 110, -1));
        panelprinttt.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 290, 10));

        txxt_sgst1.setText("SGST 18%");
        panelprinttt.add(txxt_sgst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 70, -1));

        txxt_total1.setText("Reciver Signature");
        panelprinttt.add(txxt_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, 120, -1));

        txxt_remarkget.setText("Remark : ");
        panelprinttt.add(txxt_remarkget, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 270, 20));

        txxt_totalamount.setText("Total");
        panelprinttt.add(txxt_totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 110, -1));
        panelprinttt.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 270, 10));

        txxt_total4.setText("Total In Words : ");
        panelprinttt.add(txxt_total4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, -1));

        txxt_total5.setText("Remark : ");
        panelprinttt.add(txxt_total5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 90, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel12.setText("Sonopant  Dandekar Shikshan Mandali's");
        panelprinttt.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 520, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Sonopant  Dandekar Arts, V.S Apte Commerce & M.H Mehta Science College");
        panelprinttt.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 630, 40));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Tal.Dist.Palghar.Pin-401602");
        panelprinttt.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 230, 30));

        getContentPane().add(panelprinttt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 840, 900));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Print  Receipt");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        setSize(new java.awt.Dimension(2037, 1073));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewMouseEntered
        Color clr = new Color(0, 153, 153);
        Panelview.setBackground(clr);
    }//GEN-LAST:event_btnviewMouseEntered

    private void btnviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewMouseExited
        Color clr = new Color(0, 102, 102);
        Panelview.setBackground(clr);
    }//GEN-LAST:event_btnviewMouseExited

    private void PanelviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelviewMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelviewMouseEntered

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        Color clr = new Color(0, 153, 153);
        Panelback.setBackground(clr);
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        Color clr = new Color(0, 102, 102);
        Panelback.setBackground(clr);
    }//GEN-LAST:event_btnbackMouseExited

    private void PanelbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelbackMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelbackMouseEntered

    private void btnsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseEntered
        Color clr = new Color(0, 153, 153);
        Panesearch.setBackground(clr);
    }//GEN-LAST:event_btnsearchMouseEntered

    private void btnsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseExited
        Color clr = new Color(0, 102, 102);
        Panesearch.setBackground(clr);
    }//GEN-LAST:event_btnsearchMouseExited

    private void PanesearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanesearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanesearchMouseEntered

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
        Color clr = new Color(0, 153, 153);
        Paneledit.setBackground(clr);
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
        Color clr = new Color(0, 102, 102);
        Paneledit.setBackground(clr);
    }//GEN-LAST:event_btneditMouseExited

    private void PaneleditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneleditMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PaneleditMouseEntered

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        Color clr = new Color(0, 153, 153);
        Panellogout.setBackground(clr);
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        Color clr = new Color(0, 102, 102);
        Panellogout.setBackground(clr);
    }//GEN-LAST:event_btnlogoutMouseExited

    private void PanellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanellogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanellogoutMouseEntered

    private void btnhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseEntered
        Color clr = new Color(0, 153, 153);
        Panelhome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseEntered

    private void btnhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseExited
        Color clr = new Color(0, 103, 103);
        Panelhome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseExited

    private void PanelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelhomeMouseEntered

    }//GEN-LAST:event_PanelhomeMouseEntered

    private void btncourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncourseMouseEntered
        Color clr = new Color(0, 153, 153);
        Panelcourse.setBackground(clr);
    }//GEN-LAST:event_btncourseMouseEntered

    private void btncourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncourseMouseExited
        Color clr = new Color(0, 102, 102);
        Panelcourse.setBackground(clr);
    }//GEN-LAST:event_btncourseMouseExited

    private void PanelcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelcourseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelcourseMouseEntered

    private void btnprintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseEntered
        Color clr = new Color(0, 153, 153);
        panelprint.setBackground(clr);
    }//GEN-LAST:event_btnprintMouseEntered

    private void btnprintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseExited
        Color clr = new Color(0, 102, 102);
        panelprint.setBackground(clr);
    }//GEN-LAST:event_btnprintMouseExited

    private void panelprintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelprintMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelprintMouseEntered

    private void btnedditlastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnedditlastMouseEntered
        Color clr = new Color(0, 153, 153);
        paneleditlast.setBackground(clr);
    }//GEN-LAST:event_btnedditlastMouseEntered

    private void btnedditlastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnedditlastMouseExited
        Color clr = new Color(0, 102, 102);
        paneleditlast.setBackground(clr);
    }//GEN-LAST:event_btnedditlastMouseExited

    private void paneleditlastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditlastMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_paneleditlastMouseEntered

    private void btnprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47, 0.47);

                panelprinttt.print(g2);    //reciept print page ka variable name ayega 

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnprintMouseClicked

    private void btnedditlastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnedditlastMouseClicked
        UpdateFeesDetails update = new UpdateFeesDetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnedditlastMouseClicked

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked
        home house=new home();
        house.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhomeMouseClicked

    private void btnsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseClicked
        SearchRecord search=new SearchRecord();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsearchMouseClicked

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
        EditCourse editCourse=new EditCourse();
        editCourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btneditMouseClicked

    private void btnviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewMouseClicked
        ViewAllRecord record=new ViewAllRecord();
        record.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnviewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelback;
    private javax.swing.JPanel Panelcourse;
    private javax.swing.JPanel Paneledit;
    private javax.swing.JPanel Panelhome;
    private javax.swing.JPanel Panellogout;
    private javax.swing.JPanel Panelsidebar;
    private javax.swing.JPanel Panelview;
    private javax.swing.JPanel Panesearch;
    private javax.swing.JLabel btnback;
    private javax.swing.JLabel btncourse;
    private javax.swing.JLabel btnedditlast;
    private javax.swing.JLabel btnedit;
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JLabel btnprint;
    private javax.swing.JLabel btnsearch;
    private javax.swing.JLabel btnview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblbankname;
    private javax.swing.JLabel lblchequename;
    private javax.swing.JPanel paneleditlast;
    private javax.swing.JPanel panelprint;
    private javax.swing.JPanel panelprinttt;
    private javax.swing.JLabel txt_receiptNo;
    private javax.swing.JLabel txxt_bankname;
    private javax.swing.JLabel txxt_cgst;
    private javax.swing.JLabel txxt_chequeDDno;
    private javax.swing.JLabel txxt_coursenaame1;
    private javax.swing.JLabel txxt_dash;
    private javax.swing.JLabel txxt_date;
    private javax.swing.JLabel txxt_getcgst;
    private javax.swing.JLabel txxt_getsgst;
    private javax.swing.JLabel txxt_gstinn;
    private javax.swing.JLabel txxt_initialamount;
    private javax.swing.JLabel txxt_paymentMode;
    private javax.swing.JLabel txxt_recivedfrom;
    private javax.swing.JLabel txxt_remarkget;
    private javax.swing.JLabel txxt_sgst1;
    private javax.swing.JLabel txxt_total1;
    private javax.swing.JLabel txxt_total4;
    private javax.swing.JLabel txxt_total5;
    private javax.swing.JLabel txxt_totalamount;
    private javax.swing.JLabel txxt_totalinwordsss;
    private javax.swing.JLabel txxt_year1;
    private javax.swing.JLabel txxt_year2;
    // End of variables declaration//GEN-END:variables
}
